services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: blogvibe
    ports:
      - "8010:8000"
    volumes:
       - .:/app
    networks:
      - blogvibe-network
    depends_on:
      - mongo  

  mongo:
    image: mongo
    container_name: mongo
    ports: 
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - blogvibe-network
      
  # redis:
  #   image: redis
  #   container-name: redis
  #   command: ["redis-server", "--requirepass", "password"]
  #   ports: 
  #     - "6379:6379"
  #   volumes:
  #     - redis-data:/data
  #   networks:
  #     - todo-network

networks:
  blogvibe-network:
    external: true

volumes:
  mongo-data: